version: '3.9'

services:
  database:
    container_name: postgres_db
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: file_store
    ports:
      - "5437:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: